include_defs('//bucklets/maven_jar.bucklet')

VER = '2.12.6'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  sha1 = '2256f4aea112d3b5ff7e17a70e74140b7fe860ab',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  attach_source = False,
  repository = REPO,
  license = 'Apache2.0',
)
